format = "$directory$character"
right_format = """$nix_shell$git_status$git_branch$cmd_duration"""

# Enable the blank line at the start of the prompt
add_newline = true

[line_break]
disabled = false

[character]
success_symbol = " [ğŸ¤](#f5c2e7 bold)"
error_symbol = " [ğŸ¤](#f38ba8)"

[hostname]
disabled = true

[cmd_duration]
min_time = 1
format = "(fg:#1e1e2e bg:#1e1e2e)[î‚¶](fg:#cba6f7 bg:#1e1e2e)[ï‰’ $duration](fg:#1e1e2e bg:#cba6f7)[î‚´](fg:#cba6f7 bg:none) "
disabled = false
style = "fg:#cba6f7 bg:#1e1e2e"

[directory]
format = " (fg:#1e1e2e bg:#1e1e2e)[î‚¶](fg:#f5c2e7 bg:#1e1e2e)[ï» $path](fg:#1e1e2e bg:#f5c2e7)[î‚´](fg:#f5c2e7 bg:none) "
style = "fg:#d9d7d6 bg:#1e1e2e"
truncation_length = 3
truncate_to_repo=true

[nix_shell]
format = "(fg:#1e1e2e bg:#1e1e2e)[î‚¶](fg:#94e2d5 bg:#1e1e2e)[ï‹œ](fg:#1e1e2e bg:#94e2d5)[î‚´](fg:#94e2d5 bg:none) "
style = "fg:#94e2d5 bg:#1e1e2e"

[git_branch]
format = "(fg:#1e1e2e bg:#1e1e2e)[î‚¶](fg:#f5e0dc bg:#1e1e2e)[ï˜ $branch](fg:#282c34 bg:#f5e0dc)[î‚´](fg:#f5e0dc bg:none) "
style = "fg:#f5e0dc bg:#1e1e2e"

[git_status]
format="(fg:#1e1e2e bg:#1e1e2e)[î‚¶](fg:#f2cdcd bg:#1e1e2e)[ï„“ $all_status](fg:#1e1e2e bg:#f2cdcd)[î‚´](fg:#f2cdcd bg:none) "
style = "fg:#f2cdcd bg:#1e1e2e"
conflicted = "="
ahead ="ï„†${count}"
behind = "ï„‡${count}"
diverged = "ï„†${ahead_count}ï„‡${behind_count}"
up_to_date = "ï˜«"
untracked = "?${count}"
stashed = "ï£•"
modified = "!${count}"
staged = "+${count}"
renamed = "Â»${count}"
deleted = "ïš¿${count}"

[package]
disabled=true
